config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
    end

    authenticated :user do
      root 'users#show', as: :authenticated_root
    end

    # delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  scope 'fake_fb' do
    devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }
  end

  resources :users

  resources :relationships, only: [:create, :destroy]
  resources :posts, only: [:new, :create, :edit, :update, :index]
  resources :comments, only: [:create, :update, :destroy]
  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :delete
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :liker, class_name: "User"

  validates :liker_id, uniqueness: { scope: :post_id }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  respond_to :js, :json, :html

  def like
    @user = current_user
    @post = Post.find(params[:post_id])
    like = @user.like!(@post)
    flash[:success] = "You liked the post"
    #redirect_back_to posts_path
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def unlike
    @user = current_user
    @like = @user.likes.find_by_post_id(params[:post_id])
    @post = Post.find(params[:post_id])
    @like.destroy!
    flash[:success] = "You unliked the post"
    #redirect_back_to posts_path
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_button.html.erb
<% if current_user.like?(post) %>
  <%#= render 'likes/unlike'%>
  <%= button_to "Unlike", unlike_path(post_id: post.id), remote: true, method: :delete  %>
<% else %>
  <%#= render 'likes/like'%>
  <%= button_to "Like", like_path(post_id: post.id), remote: true  %>
<% end %>

app/views/likes/_like.html.erb
<%= form_for(@user, url: like_path(post_id: post.id), remote: true) do |f| %>
  <div><%= hidden_field_tag :post_id, post.id %></div>
  <%= f.submit "Like" %>
<% end %>

app/views/likes/_unlike.html.erb
<%= form_for(@user, url: unlike_path(post_id: post.id), html: { method: true }, remote: true) do |f| %>
  <div><%= hidden_field_tag :post_id, post.id %></div>
  <%= f.submit "Unlike" %>
<% end %>

app/views/likes/like.js.erb
$('div#<%= dom_id(@post) %>').html('<%= j render partial: "button", locals: {post: @post} %>');

app/views/likes/unlike.js.erb
$("#post_<%= @post.id %>").html('<%= escape_javascript("button") %>');